version: '3.5'
services:

  proxy:
    build: ./proxy
    depends_on:
      - backend
    ports:
      - "81:81"
    networks:
      - network1

  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - "5000:5000"
    networks:
      - network1
      - network2

  database:
    build: ./database
    networks:
      - network2

networks:
  network1:
    name: 'network1'
  network2:
    name: 'network2'
